language: c

sudo: false

matrix:
  include:
  - env: ARGS="--stack-yaml stack-ghc-7.8.4.yaml"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: ARGS="--stack-yaml stack-ghc-7.10.3.yaml"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: ARGS= GHCVER=8.0.1
    addons: {apt: {packages: [libgmp-dev]}}

cache:
  directories:
  - $HOME/.stack

before_install:
- export PATH=$HOME/.local/bin:$HOME/.cabal/bin:$PATH
- mkdir -p ~/.local/bin
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- stack --version

install:
- stack ${ARGS} setup --no-terminal
- stack ${ARGS} build --no-terminal --only-snapshot --test --no-run-tests;

script:
- stack ${ARGS} test --test-arguments='--plain'

notifications:
  slack:
    secure: g0NP1tkOe3+kI6O0Q1mgT/jPaLjxQ31J26MWouicu2F1Y3p73qTvv/QsOkafRMZDn07HlzgviCP25r7Ytg32pUAFvOh4U4MT2MpO0jUVVGPi4ZiwB+W5AH+HlDtJSickeSZ0AjXZSaGv8nQNegWkeaLQgLBIzrTHU8s0Y9K+whQ=
