resolver: nightly-2016-06-09

packages:
- '.'
- location:
    git: https://github.com/haskell-distributed/distributed-process-systest.git
    commit: 317026b17b94c40318f449674efbed6802cc9ec4
  extra-dep: true

extra-deps:
- rank1dynamic-0.3.3.0
- distributed-static-0.3.5.0
- network-transport-0.4.4.0
- network-transport-tcp-0.5.1
- network-transport-inmemory-0.5.1
- distributed-process-0.6.6
- rematch-0.2.0.0
