resolver: nightly-2016-03-02
packages:
- .
- location:
    git: https://github.com/haskell-distributed/distributed-process-systest.git
    commit: 6b8749fd38141425e6b677d5a5137b3fe09cc127

extra-deps:
- rank1dynamic-0.3.2.0
- distributed-static-0.3.4.0
- distributed-process-0.6.1
- network-transport-tcp-0.4.3.1
- rematch-0.2.0.0

